Updated app name
appleprtest/appleprtest pull request #6
Opened 2017-03-04 04:49 UTC by appleprtest

The app hasn't been called Pocket Trailer in a while. This PR fixes that.

2017-03-04 05:05 UTC, ptsochantaris commented
This is a comment

2017-03-04 05:10 UTC, ptsochantaris reviewed
Comment Review Changed

2017-03-04 06:14 UTC, ptsochantaris reviewed
Another comment review

2017-03-10 18:00 UTC, ptsochantaris submitted a review, later dismissed
Blocker

2017-03-25 15:58 UTC, ptsochantaris reviewed
Another review comment

2017-03-25 16:34 UTC, ptsochantaris requested changes
WAT

2017-03-25 16:35 UTC, ptsochantaris approved these changes

2017-04-05 19:26 UTC, ptsochantaris submitted a review, later dismissed
Change this please

2017-06-11 12:10 UTC, ptsochantaris commented
Another comment

2017-06-11 12:13 UTC, ptsochantaris commented
Another comment

2017-06-11 12:16 UTC, ptsochantaris commented
Another comment

2018-07-01 18:35 UTC, appleprtest commented
Comment

2018-07-01 19:01 UTC, appleprtest reviewed
WAT

2018-07-01 19:03 UTC, ptsochantaris submitted a review, later dismissed
Change

2018-07-01 19:08 UTC, ptsochantaris submitted a review, later dismissed

2018-07-01 19:22 UTC, ptsochantaris submitted a review, later dismissed
Testing

2018-09-19 07:55 UTC, ptsochantaris approved these changes

2019-12-16 19:38 UTC, ptsochantaris approved these changes

2019-12-16 19:38 UTC, ptsochantaris commented on README.md
> -Testing PRs for Pocket Trailer.
Review comment X

2019-12-16 19:38 UTC, ptsochantaris commented on README.md
> -Testing PRs for Pocket Trailer.
YZ

2019-12-16 19:38 UTC, ptsochantaris commented on README.md
> -Testing PRs for Pocket Trailer.
zzzz

2019-12-16 19:38 UTC, ptsochantaris commented on README.md
> -Testing PRs for Pocket Trailer.
zzzzzzzzz

2019-12-24 11:09 UTC, ptsochantaris commented
Test close

2019-12-24 11:09 UTC, closed without merging

2019-12-24 11:32 UTC, ptsochantaris commented
Comment on closed item

2019-12-24 11:39 UTC, ptsochantaris commented
Another comment

2019-12-24 11:41 UTC, ptsochantaris commented
Comment 3

2019-12-24 12:05 UTC, ptsochantaris commented
Comment 4

2019-12-24 12:08 UTC, appleprtest commented
Comment 5

2019-12-24 12:11 UTC, appleprtest commented
Comment 6

2019-12-24 12:19 UTC, ptsochantaris commented
Comment 7

2019-12-24 17:10 UTC, appleprtest commented
Comment 8

2019-12-24 18:04 UTC, appleprtest commented
Comment 9

2019-12-24 18:11 UTC, ptsochantaris commented
Comment 10